name: Pylint

on:
#  push:
#    branches:
#      #- 'main' # TODO re-enable this one day after pylint works
#      #- 'releases/**'
  # pull_request:
  #   branches:
  #     - 'main' # TODO also
  workflow_dispatch

jobs:
  lint-pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      # run this but disable it from causing failure. already not required but still annoying
      continue-on-error: true
      run: |
        pylint $(git ls-files '*.py')
