name: Pytest

on:
  push:
    branches:
      - 'main'
      #- 'releases/**'
  pull_request:
    branches:
      - 'main'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Install ffmpeg
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: ffmpeg
        version: 1.0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run pytest
      run: |
        coverage run -m pytest -n 10

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - uses: actions/upload-artifact@v3
      if: '!cancelled()'
      with:
        name: tests
        path: /tmp/pytest-of-runner/pytest-0/
